Kelompok1/urls.py
from django.contrib import admin
from django.urls import path, include
from crowdfunding.views import daftar

urlpatterns = [
    path('admin/', admin.site.urls),
	path('', include('homePage.urls')),
    path('crowd/', include(('crowdfunding.urls', 'crowdfunding'), namespace = "crowdfunding")),
    path('viewmore/', include('viewmore.urls')),
    path('history/', include('history.urls')),
    path('auth/', include('social_django.urls', namespace='social')),
]

crowdfunding/urls.py
from django.urls import path
from django.conf.urls import url, include
from django.contrib.auth import views
from .views import *
from django.conf import settings

urlpatterns = [
	path('daftar', daftar, name = 'daftar'),
	path('logout', views.LogoutView.as_view(), {'next_page': settings.LOGOUT_REDIRECT_URL}, name = 'logout'),
	path('donasi', donasi, name = 'donasi'),
	path('terdonasi', savedatadonasi, name = 'terdonasi'),
    # url(r'^logout/$', views.logout, name='logout'),
    path('auth/', include('social_django.urls', namespace='social')),
]

history/urls.py
from django.urls import path
from history import views

urlpatterns = [
    path('', views.history_func,  name="history"),
]

crowdfunding/models.py
from django.db import models
from django.utils import timezone
from datetime import date
# Create your models here.
class Model_Daftar(models.Model):
	nama = models.CharField(max_length=200)
	tanggal_lahir = models.DateField(max_length=200)
	email = models.EmailField(unique = True)
	password = models.CharField(max_length = 200)
	

class Model_Donasi(models.Model):
	nama_program = models.CharField(max_length=200)
	nama = models.CharField(max_length = 200)
	email = models.EmailField()
	jumlah = models.IntegerField()
	
def __str__(self):
	return self.nama

crowdfunding/forms.py
from django import forms
import datetime
class Form_Daftar(forms.Form):

    error_messages = {
        'required': 'Please type',
    }

    nama_attrs = {
        'type': 'text',
        'placeholder' : 'Nama Lengkap',
        'class' : 'form-control',
    }

    tanggal_lahir_attrs = {
        'type': 'date',
        'placeholder' : 'Tanggal Lahir',
        'class' : 'form-control',
    }

    email_attrs = {
        'type': 'email',
        'placeholder' : 'Email',
        'class' : 'form-control',
    }

    password_attrs = {
        'type': 'password',
        'placeholder': 'Password',
        'class' : 'form-control'
    }

    nama = forms.CharField(label='Nama Lengkap', required=True, widget=forms.TextInput(attrs = nama_attrs))
    tanggal_lahir = forms.DateField(label='Tanggal Lahir', required=True, widget=forms.DateInput(attrs = tanggal_lahir_attrs))
    email = forms.EmailField(label='Alamat Email', required=True, widget=forms.TextInput(attrs = email_attrs))
    password = forms.CharField(required=True, widget = forms.PasswordInput(attrs = password_attrs))

class Form_Donasi(forms.Form):
    error_messages = {
        'required': 'Please type',
    }

    nama_program_attrs = {
        'type': 'text',
        'placeholder' : 'Nama Program',
        'class' : 'form-control',
    }

    nama_attrs = {
        'type': 'text',
        'placeholder' : 'Nama Lengkap',
        'class' : 'form-control',
    }

    email_attrs = {
        'type': 'email',
        'placeholder' : 'Email',
        'class' : 'form-control',
    }

    jumlah_attrs = {
        'type': 'number',
        'placeholder': 'Jumlah Donasi',
        'class' : 'form-control',
    }

    nama_program = forms.CharField(label='Nama Program', required=True, widget=forms.TextInput(attrs = nama_program_attrs))
    nama = forms.CharField(label='Nama Lengkap', required=True, widget=forms.TextInput(attrs = nama_attrs))
    email = forms.EmailField(label='Alamat Email', required=True, widget=forms.TextInput(attrs = email_attrs))
    jumlah = forms.IntegerField(required=True, widget = forms.NumberInput(attrs = jumlah_attrs))

crowdfunding/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .forms import Form_Daftar, Form_Donasi
from .models import Model_Daftar, Model_Donasi

response = {}

# Create your views here.

def daftar(request):
	response['form_daftar'] = Form_Daftar
	html = "formdaftar.html"
	response['errmsg'] = ''
	return render(request, html, response)

def savedata(request):
	form = Form_Daftar(request.POST or None)
	if (request.method == 'POST' and form.is_valid()):
		response['nama'] = request.POST['nama']
		response['tanggal_lahir'] = request.POST['tanggal_lahir']
		response['email'] = request.POST['email']
		response['password'] = request.POST['password']
		project = Model_Daftar(nama = response['nama'], tanggal_lahir = response['tanggal_lahir'], email = response['email'], password = response['password'])
			
		data = Model_Daftar.objects.all().filter(email = response['email']).count()

		if data == 0:
			project.save()
			project = Model_Daftar.objects.all()
			response['project'] = project
			html = 'terdaftar.html'
			return render (request, html, response)
		else:
			response['errmsg'] = 'email sudah terdaftar'
			html = 'formdaftar.html'
			return render (request, html, response)
	else:
		response['form_daftar'] = Form_Daftar
		response['errmsg']='input tidak valid'
		html = "formdaftar.html"
		return render(request, html, response)

def donasi(request):
	response['form_donasi'] = Form_Donasi
	response['errmsg']=''
	html = "formdonasi.html"
	return render(request, html, response)

def savedatadonasi(request):
	form = Form_Donasi(request.POST or None)
	if (request.method == 'POST' and form.is_valid()):
		response['nama_program'] = request.POST['nama_program']
		response['nama'] = request.POST['nama']
		response['email'] = request.POST['email']
		response['jumlah'] = request.POST['jumlah']
		project = Model_Donasi(nama_program = response['nama_program'], nama = response['nama'], email = response['email'], jumlah = response['jumlah'])
		project.save()
		project = Model_Donasi.objects.all()
		response['project'] = project
		html = 'history_page.html'
		response['msg']='sudah donasi'
		return render (request, html, response)
	else:
		response['form_donasi'] = Form_Donasi
		response['errmsg']='input tidak valid'
		html = "formdonasi.html"
		return render(request, html, response)

crowdfunding/templates/formdaftar.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
	<title>FUNDEE</title>
	<link rel="stylesheet" type="text/css" href="{%static 'stylesheet.css' %}"/>
	<link href="//netdna.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
	<script src="//netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
	<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
    
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<style type="text/css">
	body { padding: 2em; }


/* Shared */
.loginBtn {
  box-sizing: border-box;
  position: relative;
  /* width: 13em;  - apply for fixed size */
  margin: 0.2em;
  padding: 0 15px 0 46px;
  border: none;
  text-align: left;
  line-height: 34px;
  white-space: nowrap;
  border-radius: 0.2em;
  font-size: 16px;
  color: #FFF;
}
.loginBtn:before {
  content: "";
  box-sizing: border-box;
  position: absolute;
  top: 0;
  left: 0;
  width: 34px;
  height: 100%;
}
.loginBtn:focus {
  outline: none;
}
.loginBtn:active {
  box-shadow: inset 0 0 0 32px rgba(0,0,0,0.1);
}

/* Google */
.loginBtn--google {
  /*font-family: "Roboto", Roboto, arial, sans-serif;*/
  background: #DD4B39;
}
.loginBtn--google:before {
  border-right: #BB3F30 1px solid;
  background: url('https://s3-us-west-2.amazonaws.com/s.cdpn.io/14082/icon_google.png') 6px 6px no-repeat;
}
.loginBtn--google:hover,
.loginBtn--google:focus {
  background: #E74B37;
}
</style>
<body>
    {% include "layout/navbar.html" %}
    {% block content %}
  <h2>Login</h2>
   <br>
 <button class="loginBtn loginBtn--google">
<a href="{% url 'social:begin' 'google-oauth2' %}">Login with Google</a></button> <br>
{% endblock %}

    <br><br><br><br><br>
    {% include "layout/footer.html" %}
</body>
</html>

crowdfunding/templates/formdonasi.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
	<title>Sinar Perak</title>
  <link rel="stylesheet" type="text/css" href="{%static 'stylesheet.css' %}"/>
  <link href="//netdna.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
  <script src="//netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
  <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body>
  {% include "layout/navbar.html" %}
<br>
<section>
  <div>
        <div style="width: 30%; margin: auto;" class = "jumbotron">
          <div class="row" style="background-color: #DBF2FF">
          <h1 style="font-family: niramit; text-align: center; font-size: 40px;">Donasi</h1>
          <br>
          </div>
          <br>
          <form id="form" method="POST" action="{% url 'crowdfunding:terdonasi' %}">
            {% csrf_token %}
            {{ form_donasi.as_p }}
            <input id="submit" type="submit" class="btn btn-lg btn-info" value="Submit">
            <p>{{errmsg}}</p>
          </form>
          <a href="/" class="btn btn-default">Kembali</a>
        </div>
    </div>

</section>
<br><br><br><br><br>
{% include "layout/footer.html" %}
</body>
    
</html>